micronaut:
  application:
    name: fretes

grpc:
  server:
    health:
      enabled: true

endpoints:
  all:
    port: 8081
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS